

// movie section start 
// modified to be a class just for my own reference 
/**
 * MovieList Class
 * This class has 2 properties and numerous methods
 * Look at the Readme.md file or fill list of methods
 * @class
 * @property {string} movieID - The id of the HTML element where the list is to be displayed.
 * @property {Array} movieList - The array of movies
 * @property {function} refreash - This method removes all current elements and display the current list
 */
class movie {
// conmstructor being bulit 
constructor(movieID,movietitle, year, rating) {
  this.movieID = movieID; 
  this.title = movietitle; // done for array
  this.year = year // done for array
  this.rating = rating; // done for arrat

}

} 
// note all this was generated by mockaroo the titles only the generated by mockaroo
let movies = [
new movie (15,"The Shawshank Redemption" , 1995, 10), 
new movie (16,"The Godfather", 1972, 20 ),
new movie (17,"The Dark Knight" ,2008 ,20),
new movie (18,"Pulp Fiction", 1994, 20 ),
new movie (23,"Schindlers List", 1993, 20),
new movie (25,"The Lord of the Rings: The Return of the King" ,2003, 20),
new movie (26,"Forrest Gump ", 1994, 7),
new movie (28,"Inception", 2010, 9),
new movie (48,"The Matrix", 1999, 20), 
new movie (59, "The Silence of the Lambs", 1991, 15),
];
// movie sorted 
movies.sort((a, b) => a.movieID - b.movieID)
console.log(movies)

// the value we are searching for 
let key = 72;
// orginal key was 45; but for the purposes of testing i had to chnage the key to 99 to show the not found case.


// parameter: array: to search and key to be found 
// creating the search function here 
function sequentialSearch(movies, key){ 
    console.log('sequential search');
    let found = null;
    
    for( let i = 0; i < movies.length; i++){
        if (movies[i].movieID === key){
            found = i;
            break; // stops when found
        }
    } 
    return found;
}  

// function calling 
const result = sequentialSearch(movies, key);
// ouputs result 
if (result == null){
    console.log(`the key of ${key} was not found in the array`)
} else {
    console.log(`the key of ${key} was found at index ${result}`)
}
/* moakcarro data 
*The Shawshank Redemption, The Godfather, The Dark Knight, Pulp Fiction, Schindler's List, The Lord of the Rings: The Return of the King, Forrest Gump, Inception, The Matrix, The Silence of the Lambs the ratings and years where made by my as i couldnt get mockarro to do that
*
*
*
*/


