/**
 * MovieList Class
 * This class has 2 properties and numerous methods
 * Look at the Readme.md file or fill list of methods
 * @class
 * @property {string} movieID - The id of the HTML element where the list is to be displayed.
 * @property {Array} movieList - The array of movies
 * @property {function} refreash - This method removes all current elements and display the current list
 */
class movie {
// conmstructor being bulit 
constructor(movieID,movietitle, year, rating) {
  this.movieID = movieID; 
  this.title = movietitle; // done for array
  this.year = year // done for array
  this.rating = rating; // done for arrat

}

} 
// note all this was generated by mockaroo the titles only the generated by mockaroo
let movies = [
new movie (15,"The Shawshank Redemption" , 1995, 10), 
new movie (16,"The Godfather", 1972, 20 ),
new movie (17,"The Dark Knight" ,2008 ,20),
new movie (18,"Pulp Fiction", 1994, 20 ),
new movie (23,"Schindlers List", 1993, 20),
new movie (25,"The Lord of the Rings: The Return of the King" ,2003, 20),
new movie (26,"Forrest Gump ", 1994, 7),
new movie (28,"Inception", 2010, 9),
new movie (48,"The Matrix", 1999, 20), 
new movie (59, "The Silence of the Lambs", 1991, 15),
];

// 1. use getElementByID() to create a cont var for the ordered list element.
// 2. create a for loop to loop over all movies inside of movies array.
// 3. use createElement() to create a new list element and assign it to a variable.
// 4.a use variable of assinged list element and target the innerText property.
// 4.b then assign the element from the movies array to the above: eg list.innerText = movies[index]
// 5 then target ordered list and use appendChild() with list element: eg movieList.appendChild(list)

// getting element by id 

const list = document.getElementById("list")
console.log(list)
// for loop

for (let i = 0; i < movies.length; i++) {
console.log(movies[i]) // [{movieID, title, year, rating}]
  let  li  = document.createElement("li");
  li.setAttribute("class", "row")
  li.innerText = `${movies[i].movieID}, ${movies[i].title}, ${movies[i].year}, ${movies[i].rating} `;
  list.appendChild(li); 

};

// focus on 1.3 AND 4 FROM SESSION  3 = ARRAYS AND OBJECTS
// FOCUS ON SESSION 4 FOR DOM MANIPULATION & EVENTS
//  targeting innertext //




