

// movie section start 
// modified to be a class just for my own reference 
/**
 * MovieList Class
 * This class has 2 properties and numerous methods
 * Look at the Readme.md file or fill list of methods
 * @class
 * @property {string} movieID - The id of the HTML element where the list is to be displayed.
 * @property {Array} movieList - The array of movies
 * @property {function} refreash - This method removes all current elements and display the current list
 */
class movie {
// conmstructor being bulit 
constructor(movieID,movietitle, year, rating) {
  this.movieID = movieID; 
  this.title = movietitle; // done for array
  this.year = year // done for array
  this.rating = rating; // done for arrat

}

} 
// note all this was generated by mockaroo the titles only the generated by mockaroo
let movies = [
new movie ("The Shawshank Redemption" , 1995, 10), 
new movie ("The Godfather", 1972, 20 ),
new movie ("The Dark Knight" ,2008 ,20),
new movie ("Pulp Fiction", 1994, 20 ),
new movie ("Schindlers List", 1993),
new movie ("The Lord of the Rings: The Return of the King" ,2003, 20),
new movie ("Forrest Gump, ", 1994, 7),
new movie ("Inception", 2010, 9),
new movie ("The Matrix", 1999, 20), 
new  movie ("The Silence of the Lambs", 15 ),
];
console.log(movies)
/* moakcarro data 
*The Shawshank Redemption, The Godfather, The Dark Knight, Pulp Fiction, Schindler's List, The Lord of the Rings: The Return of the King, Forrest Gump, Inception, The Matrix, The Silence of the Lambs the ratings and years where made by my as i couldnt get mockarro to do that
*
*
*
*/


